name: booking_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.10.0
  provider: ^6.0.0
  http: ^0.13.3
  image_picker: ^0.8.4
  shared_preferences: ^2.0.7
  bubble_tab_indicator: ^0.1.6
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.9
  intl: ^0.15.8
  simple_animations: ^1.3.3
  animated_splash_screen: ^1.1.0
  carousel_slider: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  animated_text: ^1.0.1
  flutter_svg: ^0.22.0
  multiavatar: ^0.1.5
  # font_awesome_flutter: ^9.2.0
  badges: ^2.0.2

  # animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.7.2


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700